## First Project Kaggle Api

In [10]:
!pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (1.8.2)
Requirement already satisfied: black>=24.10.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (25.12.0)
Requirement already satisfied: bleach in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: kagglesdk in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (0.1.13)
Requirement already satisfied: mypy>=1.15.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (1.19.1)
Requirement already satisfied: protobuf in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (6.33.1)
Requirement already satisfied: python-dateutil in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: tqdm in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: types-requests in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (2.32.4.20250913)
Requirement already satisfied: types-tqdm in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (4.67.0.20250809)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: click>=8.0.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from black>=24.10.0->kaggle) (8.3.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from black>=24.10.0->kaggle) (1.1.0)
Requirement already satisfied: packaging>=22.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from black>=24.10.0->kaggle) (25.0)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from black>=24.10.0->kaggle) (0.12.1)
Requirement already satisfied: platformdirs>=2 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from black>=24.10.0->kaggle) (4.3.8)
Requirement already satisfied: pytokens>=0.3.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from black>=24.10.0->kaggle) (0.3.0)
Requirement already satisfied: colorama in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from click>=8.0.0->black>=24.10.0->kaggle) (0.4.6)
Requirement already satisfied: typing_extensions>=4.6.0 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from mypy>=1.15.0->kaggle) (4.14.1)
Requirement already satisfied: librt>=0.6.2 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from mypy>=1.15.0->kaggle) (0.7.4)
Requirement already satisfied: webencodings in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from requests->kaggle) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from requests->kaggle) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sunain khan\appdata\roaming\python\python313\site-packages (from requests->kaggle) (2025.8.3)

In [18]:
import kaggle
!"C:/Users/Sunain khan/AppData/Roaming/Python/Python313/Scripts/kaggle.exe" datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to D:\CDE Course\Projects\Project 1

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 422kB/s]
100%|##########| 200k/200k [00:00<00:00, 421kB/s]

In [17]:
import pandas as pd
df = pd.read_csv(r'D:\CDE Course\Projects\Project 1\Datasets\orders.csv', na_values=['Not Available','unknown'])
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [39]:
# Change clolumns name

In [23]:
df.rename(columns={'Order Id': 'order_id_number', 'City': 'city_name'})
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [19]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ', '_')
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [20]:
df['discount']= df['list_price']* df['discount_percent'] * .01
df['sale_price'] = df['list_price']-df['discount']
df['profit'] = df['sale_price']- df['cost_price']
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [21]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [22]:
df.drop(columns=['discount_percent', 'cost_price'], inplace= True)

## Upload to sql server

In [6]:
import sqlalchemy as sal

In [27]:
engine = sal.create_engine('mssql://DESKTOP-L49V2CE/FirstProject?driver=ODBC+Driver+17+for+SQL+Server')
conn = engine.connect()

In [28]:
## Load the data into sql server with the help of append option
df.to_sql('df_orders', con=conn , index=False, if_exists='replace')

31